

const char *bookNames[] = {
    "Solo Leveling",
    "The Beginning After The End",
    "Omniscient Reader",
    "Eleceed",
    "Tower of God",
    "The Boxer",
    "Wind Breaker",
    "Nano Machine",
    "Legend of the Northern Blade",
    "Mercenary Enrollment",
    "Return of the Mount Hua Sect",
    "SSS-Class Suicide Hunter",
    "Doom Breaker",
    "Greatest Estate Developer",
    "Leviathan",
    "Lookism",
    "Weak Hero",
    "Player Who Can't Level Up",
    "Second Life Ranker",
    "Skeleton Soldier Couldn't Protect the Dungeon",
    "The World After the Fall",
    "Murim Login",
    "Academy's Genius Swordmaster",
    "Overgeared",
    "The Return of the Crazy Demon"
};

const char *authorFname[] = {
    "Chugong",
    "TurtleMe",
    "Sing",
    "Jeho",
    "SIU",
    "JH",
    "Yongseok",
    "Hanjung",
    "Woo",
    "YC",
    "Biga",
    "Sinnoa",
    "Blue",
    "Lee",
    "Lee",
    "Park",
    "SEOPASS",
    "Wine",
    "Sa",
    "Sosori",
    "Sing",
    "Zero",
    "Seo",
    "Park",
    "Yu"
};

char authorMname[] = {
    'A','A','A','A','A',
    'A','A','A','A','A',
    'A','A','A','A','A',
    'A','A','A','A','A',
    'A','A','A','A','A'
};

const char *authorLname[] = {
    "Jang",
    "Lee",
    "Song",
    "Son",
    "Lee",
    "Kim",
    "Jo",
    "Han",
    "Park",
    "Rak",
    "Kim",
    "Park",
    "Dragon",
    "Hyun",
    "Gyuntak",
    "Taejun",
    "Kim",
    "Cheese",
    "Doyeon",
    "Ant",
    "S",
    "Biglife",
    "Gwon",
    "Saenal",
    "JP"
};

float ratings[] = {
    9.9,
    9.8,
    9.9,
    9.8,
    9.7,
    9.8,
    9.6,
    9.7,
    9.8,
    9.7,
    9.9,
    9.8,
    9.7,
    9.9,
    9.6,
    9.4,
    9.5,
    9.4,
    9.5,
    9.3,
    9.4,
    9.5,
    9.3,
    9.4,
    9.5
};
